bas1 = {'apple','banana','mango','apple','grape'}
bas2 = {'mango','kiwi','banana','kiwi'}
print("Basket1:",bas1)
print("Basket2:",bas2)
bas1.add('orange')
print("Basket 1 after adding orange:",bas1)
common_fruits = bas1.intersection(bas2)
print('Fruits in both baskets:',common_fruits)
import array as arr
fruit_count = arr.array('i',[3,5,2,4])
print("Fruit counts array:",fruit_count)
fruit_count.insert(0,1)
fruit_count.append(6)
print('Fruits counts after adding items:',fruit_count)
count_of_4 = fruit_count.count(4)
print("No. of times 4 appears:",count_of_4)
fruit_count.reverse()
print("Reverse fruit counts array",fruit_count)
print("")
print("====CLASS FRUIT BASKET ORGANIZER====")
print("Basket1",bas1)
print("Basket1",bas2)
print("shared fruits",common_fruits)
print("fruit count",fruit_count)
print("===============================")
